### ISSUE TITLE
When updating .js files gulp does not rebuild site.

### ISSUE THREAD

**Issue by jacebenson** [M-C-C/M-C-C.github.io#16]
When updating .js files gulp does not rebuild site.

**Comment by jacebenson** [comment]
Workaround, ctrl + c, re-run `gulp serve`
OR 
Update a html file

**Comment by Brekmister** [comment]
Which js files are you updating?

**Comment by jacebenson** [comment]
I had made js files in new folders, so this really can be closed but we should update the readme or something with where things are watched by default.
